deploy_production:
    stage: deploy
    image: kroniak/ssh-client
    environment: TESTNET-DEV
    script:
        - touch deploy_pionux
        - echo "$deploy_pionux" > deploy_pionux && chmod +x deploy_pionux
        - ./deploy_pionux
    only:
        - master