
sudo: false
language: node_js
node_js:
- '8'
addons:
  ssh_known_hosts: 165.22.251.128
branches:
  only:
  - master
cache:
  directories:
  - ~/.npm
  - node_modules
before_install:
- cd website
- npm update
before_script:
- sleep 4
install:
- npm install
script:
- npm run start
- sleep 4