# run as Node_js
# sudo: false
# language: node_js
# node_js:
# - '8'
# addons:
#   ssh_known_hosts: 165.22.251.128
# branches:
#   only:
#   - master
# cache:
#   directories:
#   - ~/.npm
#   - node_modules
# before_install:
# - cd website
# - npm update
# before_script:
# - sleep 4
# install:
# - npm install
# script:
# - npm run start
# - sleep 4

# run as docker-compose 
sudo: required

language: minimal
branchs:
  only:
  - master
# before_install:
#     - ssh-add - <<< "${HOST_CERT}"
# after_success:
#     - chmod 600 ~/.ssh/id_rsa   
    # - ssh root@$HOST_SERVER 
    # - docker-compose up -d
    # - docker ps -a

script:
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rm -rf /.ssh/id_rsa
    - echo "$HOST_CERT" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - tail ~/.ssh/id_rsa
    # - ssh $USER@$HOST_SERVER "touch testfrom-travis-ci  && exit"

