
sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- cd /home/travis/build/hongsea/piox.org/website
- npm update
before_script: cd /home/travis/build/hongsea/piox.org/website
install:
- cd /home/travis/build/hongsea/piox.org/website
- npm install
script:
- npm run start
