# run as Node_js
# sudo: false
# language: node_js
# node_js:
# - '8'
# addons:
#   ssh_known_hosts: 165.22.251.128
# branches:
#   only:
#   - master
# cache:
#   directories:
#   - ~/.npm
#   - node_modules
# before_install:
# - cd website
# - npm update
# before_script:
# - sleep 4
# install:
# - npm install
# script:
# - npm run start
# - sleep 4

# run as docker-compose 
sudo: required

language: minimal
branchs:
  only:
  - master
# services:
#     - docker
# addons:
#   ssh_known_hosts: 165.22.251.128
# install:
#   - echo 'KEY' >> $HOME/.ssh/known_hosts
before_install:
    # - apt-cache madison docker-engine
    - echo $HOST_SERVER
# after_success:
#     - chmod 600 ~/.ssh/id_rsa   
#     - ssh river7527@173.255.241.13 -o StrictHostKeyChecking=no
    # - docker-compose up -d
    # - docker ps -a

# script:
#     - docker version

