
# sudo: false
# language: node_js
# node_js:
# - '8'
# addons:
#   ssh_known_hosts: 165.22.251.128
# branches:
#   only:
#   - master
# cache:
#   directories:
#   - ~/.npm
#   - node_modules
# before_install:
# - cd website
# - npm update
# before_script:
# - sleep 4
# install:
# - npm install
# script:
# - npm run start
# - sleep 4
sudo: required

language: go

services:
    - docker

before_install:
    - apt-cache madison docker-engine
  
    - sudo rm -f /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

script:
    - docker version
