language: node_js
node_js: 
  - "node"
  - "10"
  - "8"
cache: yarn
script: yarn start
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
deploy:
  # Deploy new version of eslint-config-eventbrite-legacy (but only on the "node" test matrix)
  - provider: script
    skip_cleanup: true
    script: npm publish packages/eslint-config-eventbrite-legacy
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^eslint-config-eventbrite-legacy-v.+$
      node: "node"
  - provider: script
    skip_cleanup: true
    script: npm publish packages/eslint-config-eventbrite
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^eslint-config-eventbrite-v.+$
      node: "node"
  - provider: script
    skip_cleanup: true
    script: npm publish packages/eslint-config-eventbrite-react
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^eslint-config-eventbrite-react-v.+$
      node: "node"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"
services:
  -nginx

directories:
  - node_modules