
sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
- cd /home/travis/build/hongsea/piox.org/website
- npm run start
# before_script: 
# - npm run start
install:
- npm install
script:
- npm run start
