version: 2.1
jobs:
  build:
    docker:
      - image: kroniak/ssh-client
    steps:
      - checkout
      - run:
          name: "Deploy Product"
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            echo -e "Host *\n\tLogLevel ERROR\n\n" >> ~/.ssh/config
            echo -e "Host *\n\tUserKnownHostsFile /dev/null\n\n" >> ~/.ssh/config
            echo "$HOSTCERT" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            echo $RUN > run
            chmod +x run
            ./run

      # - run:
      #     name: "Read file"
      #     command: echo $RUN > run
      # - run:
      #     name: "Give Permissions"
      #     command: chmod +x run
      # - run:
      #     name: "Execute Product"
      #     command: ./run

