version: 2
jobs:
  build:
    docker:
      - image: kroniak/ssh-client
    steps:
      - checkout
      - run:
          name: "Deploy Pionux Website"
          command: |
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
            echo -e "Host *\n\tLogLevel ERROR\n\n" >> ~/.ssh/config
            echo -e "Host *\n\tUserKnownHostsFile /dev/null\n\n" >> ~/.ssh/config
            touch deploy_pionux
            echo $deploy_pionux > deploy_pionux
            chmod +x deploy_pionux
            ./deploy_pionux
workflows:
  version: 2
  workflow:
    jobs:
    - build
