version: 2.1
jobs:
  build:
    docker:
      - image: kroniak/ssh-client
    steps:
      - checkout
      - run:
          name: "Creating Running"
          command: touch run
      - run:
          name: "Creating Running"
          command: echo $RUN > run
      - run:
          name: "Give Permissions"
          command: chmod +x run
      - run:
          name: "Execute Product"
          command: ./run

workflows:
    build:
      jobs:
        - build:
