version: 2.1
jobs:
  build:
    docker:
      - image: kroniak/ssh-client
    steps:
      - checkout
      - run:
          name: "Deploy Product"
          command: |
            touch run
            echo $RUN > run
            chmod +x run
            ./run
workflows:
  version: 2
  workflow:
    jobs:
    - build
