version: 2
jobs:
  build:
    docker:
    # - image: circleci/node:8
    - image: kroniak/ssh-client
    steps:
    - checkout
    - run: echo "nothing"

workflows:
  version: 2
  workflow:
    jobs:
    - build
